name: "Update jisyo"
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
  - cron: "15 14 1 * *"

jobs:
  dict:
    name: Dictionary update process
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Dictonary data source get
        run: bash ./source.sh
      - name: Generate dictionary
        run: ruby ./generate.rb > skk-jisyo.imas
      - name: UTF-8 with BOM generate
        run: |
          echo -en '\xef\xbb\xbf' >  skk-jisyo.imas.bom
          cat skk-jisyo.imas      >> skk-jisyo.imas.bom
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update jisyo at ${{ github.event_name }} / ${{ steps.current-time.outputs.ISOTime }}'
          add: 'skk-jisyo.imas*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Dictionary deploy process
    needs: dict
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build pages source
        run: |
          bash ./deploy.sh
      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
